backend:
  name: git-gateway
  branch: main

media_folder: 'src/assets/images'
public_folder: '/_astro'

collections:
  - name: 'post'
    label: 'Post'
    folder: 'src/content/post'
    create: true
    fields:
      - { label: 'Title', name: 'title', element: 'string' }
      - { label: 'Excerpt', name: 'excerpt', element: 'string' }
      - { label: 'Category', name: 'category', element: 'string' }
      - {
          label: 'Tags',
          name: 'tags',
          element: 'list',
          allow_add: true,
          allow_delete: true,
          collapsed: false,
          field: { label: 'Tag', name: 'tag', element: 'string' },
        }
      - { label: 'Image', name: 'image', element: 'string' }
      - { label: 'Publish Date', name: 'publishDate', element: 'datetime', required: false }
      - { label: 'Author', name: 'author', element: 'string' }
      - { label: 'Content', name: 'body', element: 'markdown' }
