site:
  name: astromvp
  site: 'https://astromvp.com'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: orcPxI47GSa-cRvY11tUe6iGg2IO_RPvnA1q95iEM3M

# Default SEO metadata
metadata:
  title:
    default: astromvp - Turn Ideas into Products Fast
    template: '%s — astromvp'
  description: "We help startups and entrepreneurs build impressive MVPs in weeks, not months. Get to market quickly and start gathering valuable feedback."
  robots:
    index: true
    follow: true
  openGraph:
    site_name: astromvp
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@astromvp'
    site: '@astromvp'
    cardType: summary_large_image

i18n:
  language: en
  textDirection: ltr

analytics:
  vendors:
    googleAnalytics:
      id: null # or "G-XXXXXXXXXX"

ui:
  theme: 'lofi' # Values: "system" | "light" | "dark" | "light:only" | "only"
